[package]
name = "lila-tablebase-bench"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
rayon = "1.10.0"
reqwest = { version = "0.12.5", features = ["blocking"] }
